#!/usr/bin/env bun
// Regenerates docs/m0/inventory.json from the current working tree.
// Usage: bun harness/m0/inventory.ts > /tmp/new.json && diff docs/m0/inventory.json /tmp/new.json
import { $ } from "bun"
import path from "node:path"

const ROOT = path.resolve(import.meta.dirname, "../..")
const tracked = (await $`git -C ${ROOT} ls-files | wc -l`.text()).trim()
const symlinks = (await $`git -C ${ROOT} ls-files -s | grep -c "^120000" || true`.text()).trim()

const inv = {
  generatedAt: new Date().toISOString(),
  commit: (await $`git -C ${ROOT} rev-parse --short HEAD`.text()).trim(),
  counts: {
    trackedFiles: Number(tracked),
    symlinkEntries: Number(symlinks),
  },
  note: "Regenerated by harness/m0/inventory.ts — compare against docs/m0/inventory.json",
}

console.log(JSON.stringify(inv, null, 2))
